### ISSUE TITLE
What kind of license?

### ISSUE THREAD

**Issue by yuhki50** [SeeedJP/Wio_cell_lib_for_Arduino#3]
Arduino is GPL, is this library also GPL?
https://github.com/arduino/Arduino/blob/master/license.txt

I would be happy if you could put the LICENSE file in this repository.

**Comment by matsujirushi** [comment]
License of Wio cell lib for Arduino is GNU GPL v2.
And I attached LICENSE file.
https://github.com/SeeedJP/Wio_cell_lib_for_Arduino/blob/master/LICENSE

**Comment by yuhki50** [comment]
Thank you!!!
