### ISSUE TITLE
Would like to add function to set DNS IP address.

### ISSUE THREAD

**Issue by ytsuboi** [SeeedJP/Wio_cell_lib_for_Arduino#4]
Some operator may not provide DNS IP address when getting connected. So, wanna function to set DNS manually by using AT+QIDNSCFG.

**Comment by matsujirushi** [comment]
https://github.com/SeeedJP/Wio_cell_lib_for_Arduino/commit/3d461f9d27068c6ff03a58a904c26bfac3285fe8
